-- Move embeddings from Azure text-embedding-3-small (1536) to Bedrock Titan Text Embeddings V2 (1024).
-- Vectors from different models are not comparable, so existing values are discarded (NULL, retype)
-- and regenerated by the backfill: `bun run --cwd packages/db backfill-embeddings`.

-- Cache is keyed on (content_hash, model); old rows are Azure vectors, so drop them.
DELETE FROM "embedding_cache";
--> statement-breakpoint
ALTER TABLE "embedding_cache" DROP CONSTRAINT IF EXISTS "embedding_cache_pkey";
--> statement-breakpoint
ALTER TABLE "embedding_cache" ADD COLUMN "model" text NOT NULL;
--> statement-breakpoint
ALTER TABLE "embedding_cache" ADD PRIMARY KEY ("content_hash", "model");
--> statement-breakpoint
DROP INDEX IF EXISTS idx_extractions_embedding;
--> statement-breakpoint
DROP INDEX IF EXISTS idx_ku_embedding;
--> statement-breakpoint
UPDATE "extractions" SET "embedding" = NULL;
--> statement-breakpoint
UPDATE "knowledge_units" SET "embedding" = NULL;
--> statement-breakpoint
UPDATE "embedding_cache" SET "embedding" = NULL;
--> statement-breakpoint
ALTER TABLE "extractions" ALTER COLUMN "embedding" TYPE vector(1024);
--> statement-breakpoint
ALTER TABLE "knowledge_units" ALTER COLUMN "embedding" TYPE vector(1024);
--> statement-breakpoint
ALTER TABLE "embedding_cache" ALTER COLUMN "embedding" TYPE vector(1024);
--> statement-breakpoint
CREATE INDEX idx_extractions_embedding ON extractions
  USING hnsw (embedding vector_cosine_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_ku_embedding ON knowledge_units
  USING hnsw (embedding vector_cosine_ops);
