// ============ Expert Profile (built during intro conversation) ============

export interface ExpertProfile {
  // Core (required for planning gate)
  expertName: string | null
  domain: string | null
  targetAudience: string | null
  // Depth (enriches interview plan)
  yearsExperience: string | null
  specializations: string[] | null
  uniqueApproach: string | null
  commonMistakes: string[] | null
  notableAchievements: string[] | null
  industriesOrContexts: string[] | null
  passionArea: string | null
  problemsTheySolve: string[] | null
}

export const EXPERT_PROFILE_FIELDS = [
  // Core
  { key: 'expertName', label: 'Name', group: 'basics' },
  { key: 'domain', label: 'Area of Expertise', group: 'basics' },
  { key: 'targetAudience', label: 'Target Audience', group: 'basics' },
  // Background
  { key: 'yearsExperience', label: 'Experience', group: 'background' },
  { key: 'specializations', label: 'Specializations', group: 'background' },
  { key: 'notableAchievements', label: 'Achievements', group: 'background' },
  { key: 'industriesOrContexts', label: 'Industries / Contexts', group: 'background' },
  // Perspective
  { key: 'uniqueApproach', label: 'Unique Approach', group: 'perspective' },
  { key: 'commonMistakes', label: 'Common Mistakes', group: 'perspective' },
  { key: 'passionArea', label: 'Passion Area', group: 'perspective' },
  { key: 'problemsTheySolve', label: 'Problems They Solve', group: 'perspective' },
] as const

export const EMPTY_EXPERT_PROFILE: ExpertProfile = {
  expertName: null,
  domain: null,
  targetAudience: null,
  yearsExperience: null,
  specializations: null,
  uniqueApproach: null,
  commonMistakes: null,
  notableAchievements: null,
  industriesOrContexts: null,
  passionArea: null,
  problemsTheySolve: null,
}

// ============ Interview Config (generated by Opus from expert intro) ============

export interface InterviewConfig {
  sections: Array<{
    title: string
    goal: string
    questions: Array<{
      text: string
      goal: string
    }>
  }>
  estimatedDurationMinutes: number
  domainContext: string
  extractionPriorities: string[]
}

// ============ Validation Result ============

export interface ValidationResult {
  meets_goal: boolean
  confidence: number
  explanation: string
  missing_aspects: string[]
  extracted_data: {
    key_points: string[]
    relevant_quotes: string[]
    metadata?: Record<string, unknown>
  }
  follow_up_questions?: string[]
}

// ============ Section Summary ============

export interface SectionSummary {
  summary: string
  key_points: string[]
  themes: string[]
  notable_quotes: string[]
  metadata: {
    completion_quality: number
    main_topics: string[]
  }
}

// ============ Knowledge Base (assembled post-interview) ============

export interface KnowledgeBase {
  domain: string
  expertName: string
  targetAudience: string
  facts: Array<{ content: string; tags: string[] }>
  procedures: Array<{ title: string; steps: string[]; conditions?: string }>
  decisionRules: Array<{ condition: string; action: string; reasoning?: string }>
  warnings: Array<{ content: string; severity: "low" | "medium" | "high" }>
  tips: Array<{ content: string; context?: string }>
  metrics: Array<{ name: string; value: string; context?: string }>
  definitions: Array<{ term: string; definition: string }>
  examples: Array<{ scenario: string; outcome: string }>
}

// ============ Tool Config (component toolkit output) ============

export interface ToolConfig {
  title: string
  description: string
  theme: {
    primaryColor: string
    accentColor: string
    icon: string
  }
  layout: ToolComponent[]
  contextLayers: ContextLayer[]
  operationsBoard?: TaskBoardConfig
}

export interface ContextLayer {
  level: number
  name: string
  type: "domain" | "expert" | "tool" | "user" | "question"
  content: string
  priority: number
}

// ============ Component Types ============

export interface BaseComponentConfig {
  id: string
  type: string
  title: string
  description?: string
  dependsOn?: string
  condition?: string
}

export interface DecisionTreeConfig extends BaseComponentConfig {
  type: "decision_tree"
  rootQuestion: string
  nodes: Array<{
    id: string
    question: string
    options: Array<{
      label: string
      nextNodeId?: string
      recommendation?: string
      explanation?: string
    }>
  }>
}

export interface ChecklistConfig extends BaseComponentConfig {
  type: "checklist"
  items: Array<{
    id: string
    text: string
    required: boolean
    helpText?: string
    category?: string
  }>
  checkedIds?: string[]
  groupByCategory: boolean
}

export interface CalculatorConfig extends BaseComponentConfig {
  type: "calculator"
  inputs: Array<{
    id: string
    label: string
    type: "number" | "select" | "toggle"
    options?: Array<{ label: string; value: number }>
    defaultValue?: number
    unit?: string
    min?: number
    max?: number
  }>
  formula: string
  resultLabel: string
  resultUnit?: string
  interpretation?: Array<{
    range: [number, number]
    label: string
    color: string
    advice: string
  }>
}

export interface InfoCardConfig extends BaseComponentConfig {
  type: "info_card"
  variant: "tip" | "warning" | "info" | "success"
  content: string
  expandable?: boolean
  details?: string
}

export interface StepByStepConfig extends BaseComponentConfig {
  type: "step_by_step"
  steps: Array<{
    id: string
    title: string
    content: string
    tips?: string[]
    warnings?: string[]
    estimatedTime?: string
  }>
  completedSteps?: string[]
}

export interface QuestionFlowConfig extends BaseComponentConfig {
  type: "question_flow"
  questions: Array<{
    id: string
    text: string
    inputType: "text" | "select" | "number" | "multiselect"
    options?: string[]
    placeholder?: string
    required: boolean
  }>
  completionPrompt: string
}

export interface CustomSection {
  heading: string
  variant: "text" | "list" | "highlight" | "quote" | "stats" | "timeline"
  content?: string
  items?: string[]
  stats?: Array<{ label: string; value: string; description?: string }>
}

export interface CustomConfig extends BaseComponentConfig {
  type: "custom"
  sections: CustomSection[]
}

export interface QuizConfig extends BaseComponentConfig {
  type: "quiz"
  mode: "knowledge_check" | "scenario"
  questions: Array<{
    id: string
    text: string
    scenario?: string
    options: Array<{
      id: string
      text: string
      correct: boolean
      explanation?: string
    }>
    multipleCorrect?: boolean
  }>
  showImmediateFeedback: boolean
  showScoreAtEnd: boolean
  passingScore?: number
  _quizAnswers?: Record<string, string[]>
}

export interface TaskBoardTask {
  id: string
  text: string
  description?: string
  frequency: "weekly" | "monthly" | "as_needed"
  linkedComponentId?: string
  linkedComponentTitle?: string
  category?: string
}

export interface TaskBoardConfig {
  id: string
  type: "task_board"
  title: string
  tasks: TaskBoardTask[]
}

export type ToolComponent =
  | DecisionTreeConfig
  | ChecklistConfig
  | CalculatorConfig
  | InfoCardConfig
  | StepByStepConfig
  | QuestionFlowConfig
  | CustomConfig
  | QuizConfig
  | TaskBoardConfig

// ============ Learning Platform (paths, units, attempts) ============

export type LearnerGoal = "basics" | "deep" | "practical"

export interface LearnerPreferences {
  instructions: string[]
  tone?: string
}

export type PathUnitKind =
  | "lesson_card"
  | "exercise_mc"
  | "exercise_fill"
  | "exercise_order"
  | "diagram"
  | "checkpoint"
  | "review"

// Planner output: milestones of unit specs. path_units rows are created from
// this sequence lazily as the learner approaches them.
export interface PathSequence {
  title: string
  estimatedWeeks: number
  milestones: Array<{
    title: string
    goal: string
    focusArea?: string
    units: Array<{
      kind: PathUnitKind
      focus: string
      sourceUnitIds: string[]
    }>
  }>
}

// Generated unit content shapes (stored in path_units.content)
export interface LessonCardContent {
  kind: "lesson_card"
  variant: "narrative" | "comparison" | "table" | "quote"
  concept: string
  body: string
  comparison?: { leftTitle: string; leftItems: string[]; rightTitle: string; rightItems: string[] }
  table?: { caption: string; headers: string[]; rows: string[][] }
  quote?: { text: string; attribution: string }
}

export interface ExerciseMCContent {
  kind: "exercise_mc"
  question: string
  options: Array<{ id: string; text: string; correct: boolean; explanation: string }>
}

export interface ExerciseFillContent {
  kind: "exercise_fill"
  // sentence with {{0}}, {{1}} placeholders for blanks
  sentence: string
  blanks: string[]           // correct term per placeholder index
  wordBank: string[]         // blanks + near-miss distractors, shuffled client-side
  explanation: string
}

export interface ExerciseOrderContent {
  kind: "exercise_order"
  prompt: string
  steps: string[]            // correct order; client shuffles for display
  explanation: string
}

// Checkpoint resolved at serve time: re-served exercises from the learner's
// weakest / stalest attempts (spaced repetition)
export interface CheckpointReviewContent {
  kind: "checkpoint_review"
  intro: string
  exercises: Array<ExerciseMCContent | ExerciseFillContent | ExerciseOrderContent>
  sourcePathUnitIds: string[]
}

export type PathUnitContent =
  | LessonCardContent
  | ExerciseMCContent
  | ExerciseFillContent
  | ExerciseOrderContent
  | CheckpointReviewContent

// ============ Extraction Types ============

export const EXTRACTION_TYPES = [
  "fact",
  "procedure",
  "decision_rule",
  "warning",
  "tip",
  "metric",
  "definition",
  "example",
  "context",
] as const
export type StandardExtractionType = (typeof EXTRACTION_TYPES)[number]
export type ExtractionType = StandardExtractionType | (string & {})

// ============ Status Enums ============

export const FORGE_STATUSES = [
  "draft",
  "planning",
  "interviewing",
  "processing",
  "generating",
  "complete",
  "archived",
] as const
export type ForgeStatus = (typeof FORGE_STATUSES)[number]

export const SECTION_STATUSES = ["pending", "active", "completed", "skipped"] as const
export type SectionStatus = (typeof SECTION_STATUSES)[number]

export const QUESTION_STATUSES = ["pending", "active", "answered", "skipped"] as const
export type QuestionStatus = (typeof QUESTION_STATUSES)[number]

// ============ SSE Event Types ============

export type SSEEvent =
  | { type: "chunk"; content: string }
  | { type: "done"; messageId: string }
  | { type: "validation"; result: ValidationResult }
  | { type: "extraction"; items: Array<{ id: string; type: ExtractionType; content: string; confidence: number }> }
  | { type: "advance"; sectionId: string; questionId: string }
  | { type: "section_complete"; sectionId: string; summary: SectionSummary }
  | { type: "interview_complete" }
  | { type: "error"; message: string }
